config/routes.rb
Rails.application.routes.draw do
  get 'games/index'

    resources :games
    root 'games#index'

    resources :game do
  resources :comments
end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :game 
  validates :mark, presence: true,
                    numericality: { greater_than:  0, less_than_or_equal_to: 10 }

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :name, presence: true,
                    length: { minimum: 3 }
def self.search(query)
  where("name like ?", "%#{query}%") 
end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    http_basic_authenticate_with name: "admin", password: "admin", only: :destroy
    

    
    
  def create
    @game = Game.find(params[:game_id])
    @comment = @game.comments.create(comment_params)
    redirect_to game_path(@game)
  end
 
    def destroy
    @game = Game.find(params[:game_id])
    @comment = @game.comments.find(params[:id])
    @comment.destroy
    redirect_to game_path(@game)
    end
    

    
 private
 def comment_params
 params.require(:comment).permit(:commenter, :body, :mark)
 end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    
     http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]
    
    
def index
  if params[:search]
    @games = Game.search(params[:search]).order("created_at DESC")
  else
    @games = Game.paginate(:page => params[:page], :per_page => 9)
  end
end
    
    def show
    @game = Game.find(params[:id])
    end
 
    def new
    @game = Game.new
    end
 
    def edit
    @game = Game.find(params[:id])
    end
    
    def create
    @game = Game.new(game_params)
 
    if @game.save
    redirect_to @game
    else
    render 'new'
    end
    end
    
    def update
    @game = Game.find(params[:id])
 
    if @game.update(game_params)
    redirect_to @game
    else
    render 'edit'
    end
    end
 
    def destroy
    @game = Game.find(params[:id])
    @game.destroy
 
    redirect_to games_path
    end
    
    private
    def game_params
    params.require(:game).permit(:name, :year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/comments/_comment.html.erb
 
<div id="com">
 <p>
  Mark:
  <%= comment.mark %>
</p>
<p>
  "<%= comment.body %>"
</p>
<p id="author">
  <strong>~</strong>
  <%= comment.commenter %>
</p>
<p id="del">
  <%= link_to 'Delete Comment', [comment.game, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@game, @game.comments.build]) do |f| %>

    <div id="form">
     <p>
    Author:
    <p><%= f.text_field :commenter %></p>
    </p>
    <p>
    Mark ( beetwen 1 and 10):
    <p><%= f.text_field :mark %></p>
  </p>
  <p>
    Comment:
    <p><%= f.text_area :body %></p>
  </p>
  <p id="addc">
    <%= f.submit %>
  </p>
  </div>
<% end %>

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
 
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game.errors.count, "error") %> prohibited
        this game from being saved:
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p id="n">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p id="n">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </p>
 
  <p id="ub">
    <%= f.submit %>
  </p>
 
<% end %>

app/views/games/edit.html.erb
<h1>Edit game</h1>
 
<%= render 'form' %>
 
 <div id="back">
<%= link_to 'Back', games_path %></div>

app/views/games/index.html.erb
<body>

<div>
<h1>List of games</h1>
 <div class = "container">
<table class="table table-default">

  <tr>
    <th>Name</th>
    <th>Year</th>
    <th colspan="2"></th>
   
  </tr>

  <% @games.each do |game| %>
    <tr c>
      <td><%= game.name %></td>
      <td><%= game.year %></td>
      <td><%= link_to 'Show', game_path(game) %></td>
      <td><%= link_to 'Edit', edit_game_path(game) %></td>
      <td><%= link_to 'Delete', game_path(game),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    
   
     <% end %>
      <% if @games.count > 8 %>
        <%= will_paginate @games %>
    <% end %>
     </table>
    </div>
  <p id="newg">  
   <%= link_to 'New game', new_game_path %>
  </p>
  <p id="search" ><%= form_tag(games_path, :method => "get", id: "search-form") do %>
  </p>
  <p>
  <%= text_field_tag :search, params[:search], placeholder: "Search Games" %>
  <div class="bs"><%= submit_tag "Search", :name => nil %></div>
<% end %>
 </p>
  
  
</table>
</div>
</body>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>
<p id="backn">
<%= link_to 'Back', games_path %>
</p>

app/views/games/show.html.erb
<div id="ny">
 <p>
  <strong>Name:</strong>
  <%= @game.name %>
</p> 
<p>
  <strong>Year:</strong>
  <%= @game.year %>
</p>
<strong>Avg Mark :</strong>
 <%= @game.comments.average(:mark) %>
<p id="but">
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>
</p>
</div>
 
<div id="cm"> 
<h2>Comments</h2>
<%= render @game.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 

</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "RateGame" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>